from . import base
from .endgame import EndGameScene
from .gameover import GameOverScene
from .levels import LevelsScene
from .main import MainScene
from .menu import MenuScene
from .pause import PauseScene
from .records import RecordsScene
from .settings import SettingsScene
from .skins import SkinsScene
