from .endgame import GameWinScene
from .gameover import GameLoseScene
from .levels import LevelScene
from .main import MainScene
from .menu import MenuScene
from .pause import PauseScene
from .records import RecordsScene
from .skins import SkinScene
from .settings import SettingsScene
