from .main_scene import MainScene
from .menu_scene import MenuScene
from .skins_scene import SkinScene
from .pause_scene import PauseScene
from .levels_scene import LevelScene
from .records_scene import RecordsScene
from .endgame_scene import GameWinScene
from .gameover_scene import GameLoseScene
from .settings_scene import SettingsScene
